from __future__ import annotations

from pathlib import Path

from aidetector.schemas import Category
from aidetector.schemas import CategoryScore, OverrideHints

from .base import DetectionContext, DetectionResult, Detector


class ProvenanceLayerDetector(Detector):
    name = "provenance_layer"

    _synthetic_keywords = (
        "ai-generated",
        "ai generated",
        "synthetic",
        "stable diffusion",
        "midjourney",
        "dall-e",
        "dalle",
        "comfyui",
        "generated by",
    )
    _authentic_keywords = (
        "camera original",
        "original capture",
        "authentic capture",
        "device capture",
        "camera model",
    )
    _provenance_markers = ("c2pa", "content credentials", "contentauth", "jumbf", "manifest")
    _signature_markers = ("signature", "certificate", "x5c", "issuer", "claim_generator")

    def _scan_text(self, media_uri: str | None) -> tuple[str, list[str]]:
        if not media_uri:
            return "", []
        path = Path(media_uri)
        if not path.exists():
            return "", []
        markers: list[str] = []
        try:
            content = path.read_bytes()[:2_000_000]
            text = content.decode("latin-1", errors="ignore").lower()
        except Exception:
            text = ""
        if any(marker in text for marker in self._provenance_markers):
            markers.append("embedded_provenance_marker")
        if any(marker in text for marker in self._signature_markers):
            markers.append("signature_marker")

        for sidecar_suffix in (".xmp", ".c2pa", ".json"):
            sidecar = path.with_suffix(sidecar_suffix)
            if sidecar.exists():
                try:
                    sidecar_text = sidecar.read_text(encoding="utf-8", errors="ignore").lower()
                    text += "\n" + sidecar_text
                    markers.append(f"sidecar:{sidecar_suffix}")
                except Exception:
                    continue
        return text, markers

    def _score_provenance(self, media_uri: str | None) -> tuple[CategoryScore, OverrideHints]:
        text, markers = self._scan_text(media_uri)
        has_provenance = any(marker in text for marker in self._provenance_markers)
        has_signature = any(marker in text for marker in self._signature_markers)
        synthetic_decl = any(keyword in text for keyword in self._synthetic_keywords)
        authentic_decl = any(keyword in text for keyword in self._authentic_keywords)

        hints = OverrideHints()
        rationale_tokens: list[str] = []
        if markers:
            rationale_tokens.extend(markers)
        if synthetic_decl:
            rationale_tokens.append("synthetic_decl")
        if authentic_decl:
            rationale_tokens.append("authentic_decl")

        if synthetic_decl and (has_provenance or has_signature):
            hints = OverrideHints(provenance_declares_synthetic_or_edited=True)
            return (
                CategoryScore(
                    risk=96.0,
                    confidence=90.0,
                    rationale="provenance: signed/declared synthetic asset",
                ),
                hints,
            )

        if synthetic_decl:
            hints = OverrideHints(provenance_declares_synthetic_or_edited=True)
            return (
                CategoryScore(
                    risk=86.0,
                    confidence=70.0,
                    rationale="provenance: synthetic declaration without strong signature",
                ),
                hints,
            )

        if has_provenance and authentic_decl:
            hints = OverrideHints(provenance_declares_authentic=True)
            return (
                CategoryScore(
                    risk=9.0,
                    confidence=84.0,
                    rationale="provenance: content credentials indicate authentic capture",
                ),
                hints,
            )

        if has_provenance:
            return (
                CategoryScore(
                    risk=28.0,
                    confidence=68.0,
                    rationale="provenance: credentials present but authenticity claim unclear",
                ),
                hints,
            )

        reason = "provenance: no verifiable provenance markers"
        if rationale_tokens:
            reason = f"{reason} ({', '.join(rationale_tokens)})"
        return (
            CategoryScore(risk=55.0, confidence=24.0, rationale=reason),
            hints,
        )

    def run(self, context: DetectionContext) -> DetectionResult:
        score = context.provided_scores.get(Category.PROVENANCE)
        if score is None:
            computed, hints = self._score_provenance(context.media_uri)
            merged_hints = OverrideHints(
                provenance_declares_synthetic_or_edited=(
                    context.override_hints.provenance_declares_synthetic_or_edited
                    or hints.provenance_declares_synthetic_or_edited
                ),
                watermark_strong_positive=context.override_hints.watermark_strong_positive,
                provenance_declares_authentic=(
                    context.override_hints.provenance_declares_authentic
                    or hints.provenance_declares_authentic
                ),
                forensic_contradiction=context.override_hints.forensic_contradiction,
            )
            return DetectionResult(scores={Category.PROVENANCE: computed}, override_hints=merged_hints)
        return DetectionResult(
            scores={Category.PROVENANCE: score},
            override_hints=context.override_hints,
        )
